"""updated post_data

Revision ID: b25c8f6b7814
Revises: 0269689e2e78
Create Date: 2025-08-22 21:14:08.992085

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b25c8f6b7814'
down_revision = '0269689e2e78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('media_type', sa.String(length=20), nullable=True))
        batch_op.drop_column('post_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_column('media_type')
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###
